### ISSUE TITLE
Error handling - BadRequest

### ISSUE THREAD

**Issue by odorcicd** [FeeFighters/samurai-client-ruby#1]
Currently, if an execution fails due to an ActiveResource error, BadRequest is rescued and processor_response is set to nil.
<code>def success?</code> will fail in this case even though you have a valid Transaction since processor_response is set to nil.

Also, why would trying to use sandbox credentials without the test flag (live environment) issue a BadRequest? 400 status is malformed syntax which the request is not, should it not return something like a 401 instead?

**Comment by jkrall** [comment]
Regarding the 400 response... we agree.  

Here's a useful resource on this exact topic:
http://stackoverflow.com/questions/4781187/http-400-bad-request-for-logical-error-not-malformed-request-syntax

We have a ticket on Samurai to switch this response to 422, based on the above discussion.
